#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BF
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Prueba")]
	public partial class PruebaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void Insertd(d instance);
    partial void Updated(d instance);
    partial void Deleted(d instance);
    partial void InsertAeropuerto(Aeropuerto instance);
    partial void UpdateAeropuerto(Aeropuerto instance);
    partial void DeleteAeropuerto(Aeropuerto instance);
    partial void InsertVuelo(Vuelo instance);
    partial void UpdateVuelo(Vuelo instance);
    partial void DeleteVuelo(Vuelo instance);
    partial void InsertPasajero(Pasajero instance);
    partial void UpdatePasajero(Pasajero instance);
    partial void DeletePasajero(Pasajero instance);
    partial void InsertContacto(Contacto instance);
    partial void UpdateContacto(Contacto instance);
    partial void DeleteContacto(Contacto instance);
    #endregion
		
		public PruebaDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["PruebaConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PruebaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PruebaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PruebaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PruebaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<d> d
		{
			get
			{
				return this.GetTable<d>();
			}
		}
		
		public System.Data.Linq.Table<Aeropuerto> Aeropuerto
		{
			get
			{
				return this.GetTable<Aeropuerto>();
			}
		}
		
		public System.Data.Linq.Table<Vuelo> Vuelo
		{
			get
			{
				return this.GetTable<Vuelo>();
			}
		}
		
		public System.Data.Linq.Table<Pasajero> Pasajero
		{
			get
			{
				return this.GetTable<Pasajero>();
			}
		}
		
		public System.Data.Linq.Table<Contacto> Contacto
		{
			get
			{
				return this.GetTable<Contacto>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Reserva.d")]
	public partial class d : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _codigo;
		
		private string _Persona;
		
		private int _Vuelo;
		
		private System.Nullable<int> _habilitado;
		
		private EntityRef<Pasajero> _Pasajero;
		
		private EntityRef<Vuelo> _Vuelo1;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodigoChanging(System.Guid value);
    partial void OncodigoChanged();
    partial void OnPersonaChanging(string value);
    partial void OnPersonaChanged();
    partial void OnVueloChanging(int value);
    partial void OnVueloChanged();
    partial void OnhabilitadoChanging(System.Nullable<int> value);
    partial void OnhabilitadoChanged();
    #endregion
		
		public d()
		{
			this._Pasajero = default(EntityRef<Pasajero>);
			this._Vuelo1 = default(EntityRef<Vuelo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo", AutoSync=AutoSync.OnInsert, DbType="UniqueIdentifier", IsPrimaryKey=true, IsDbGenerated=true)]
		public System.Guid codigo
		{
			get
			{
				return this._codigo;
			}
			set
			{
				if ((this._codigo != value))
				{
					this.OncodigoChanging(value);
					this.SendPropertyChanging();
					this._codigo = value;
					this.SendPropertyChanged("codigo");
					this.OncodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Persona", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Persona
		{
			get
			{
				return this._Persona;
			}
			set
			{
				if ((this._Persona != value))
				{
					if (this._Pasajero.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPersonaChanging(value);
					this.SendPropertyChanging();
					this._Persona = value;
					this.SendPropertyChanged("Persona");
					this.OnPersonaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vuelo", DbType="Int NOT NULL")]
		public int Vuelo
		{
			get
			{
				return this._Vuelo;
			}
			set
			{
				if ((this._Vuelo != value))
				{
					if (this._Vuelo1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnVueloChanging(value);
					this.SendPropertyChanging();
					this._Vuelo = value;
					this.SendPropertyChanged("Vuelo");
					this.OnVueloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_habilitado", DbType="Int")]
		public System.Nullable<int> habilitado
		{
			get
			{
				return this._habilitado;
			}
			set
			{
				if ((this._habilitado != value))
				{
					this.OnhabilitadoChanging(value);
					this.SendPropertyChanging();
					this._habilitado = value;
					this.SendPropertyChanged("habilitado");
					this.OnhabilitadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pasajero_d", Storage="_Pasajero", ThisKey="Persona", OtherKey="Nombre", IsForeignKey=true)]
		public Pasajero Pasajero
		{
			get
			{
				return this._Pasajero.Entity;
			}
			set
			{
				Pasajero previousValue = this._Pasajero.Entity;
				if (((previousValue != value) 
							|| (this._Pasajero.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Pasajero.Entity = null;
						previousValue.d.Remove(this);
					}
					this._Pasajero.Entity = value;
					if ((value != null))
					{
						value.d.Add(this);
						this._Persona = value.Nombre;
					}
					else
					{
						this._Persona = default(string);
					}
					this.SendPropertyChanged("Pasajero");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Vuelo_d", Storage="_Vuelo1", ThisKey="Vuelo", OtherKey="NumeroVuelo", IsForeignKey=true)]
		public Vuelo Vuelo1
		{
			get
			{
				return this._Vuelo1.Entity;
			}
			set
			{
				Vuelo previousValue = this._Vuelo1.Entity;
				if (((previousValue != value) 
							|| (this._Vuelo1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Vuelo1.Entity = null;
						previousValue.d.Remove(this);
					}
					this._Vuelo1.Entity = value;
					if ((value != null))
					{
						value.d.Add(this);
						this._Vuelo = value.NumeroVuelo;
					}
					else
					{
						this._Vuelo = default(int);
					}
					this.SendPropertyChanged("Vuelo1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Aeropuerto")]
	public partial class Aeropuerto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _Nombre;
		
		private string _Ciudad;
		
		private string _Pais;
		
		private System.Nullable<int> _habilitado;
		
		private EntitySet<Vuelo> _Vuelo;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnCiudadChanging(string value);
    partial void OnCiudadChanged();
    partial void OnPaisChanging(string value);
    partial void OnPaisChanged();
    partial void OnhabilitadoChanging(System.Nullable<int> value);
    partial void OnhabilitadoChanged();
    #endregion
		
		public Aeropuerto()
		{
			this._Vuelo = new EntitySet<Vuelo>(new Action<Vuelo>(this.attach_Vuelo), new Action<Vuelo>(this.detach_Vuelo));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ciudad", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Ciudad
		{
			get
			{
				return this._Ciudad;
			}
			set
			{
				if ((this._Ciudad != value))
				{
					this.OnCiudadChanging(value);
					this.SendPropertyChanging();
					this._Ciudad = value;
					this.SendPropertyChanged("Ciudad");
					this.OnCiudadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pais", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Pais
		{
			get
			{
				return this._Pais;
			}
			set
			{
				if ((this._Pais != value))
				{
					this.OnPaisChanging(value);
					this.SendPropertyChanging();
					this._Pais = value;
					this.SendPropertyChanged("Pais");
					this.OnPaisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_habilitado", DbType="Int")]
		public System.Nullable<int> habilitado
		{
			get
			{
				return this._habilitado;
			}
			set
			{
				if ((this._habilitado != value))
				{
					this.OnhabilitadoChanging(value);
					this.SendPropertyChanging();
					this._habilitado = value;
					this.SendPropertyChanged("habilitado");
					this.OnhabilitadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Aeropuerto_Vuelo", Storage="_Vuelo", ThisKey="Ciudad", OtherKey="Ciudad_Origen")]
		public EntitySet<Vuelo> Vuelo
		{
			get
			{
				return this._Vuelo;
			}
			set
			{
				this._Vuelo.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Vuelo(Vuelo entity)
		{
			this.SendPropertyChanging();
			entity.Aeropuerto = this;
		}
		
		private void detach_Vuelo(Vuelo entity)
		{
			this.SendPropertyChanging();
			entity.Aeropuerto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vuelo")]
	public partial class Vuelo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _Ciudad_Origen;
		
		private string _Ciudad_Destino;
		
		private System.DateTime _Fecha;
		
		private int _NumeroVuelo;
		
		private int _Precio;
		
		private string _Moneda;
		
		private System.Nullable<int> _habilitado;
		
		private EntitySet<d> _d;
		
		private EntityRef<Vuelo> _Vuelo2;
		
		private EntityRef<Vuelo> _Vuelo1;
		
		private EntityRef<Aeropuerto> _Aeropuerto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnCiudad_OrigenChanging(string value);
    partial void OnCiudad_OrigenChanged();
    partial void OnCiudad_DestinoChanging(string value);
    partial void OnCiudad_DestinoChanged();
    partial void OnFechaChanging(System.DateTime value);
    partial void OnFechaChanged();
    partial void OnNumeroVueloChanging(int value);
    partial void OnNumeroVueloChanged();
    partial void OnPrecioChanging(int value);
    partial void OnPrecioChanged();
    partial void OnMonedaChanging(string value);
    partial void OnMonedaChanged();
    partial void OnhabilitadoChanging(System.Nullable<int> value);
    partial void OnhabilitadoChanged();
    #endregion
		
		public Vuelo()
		{
			this._d = new EntitySet<d>(new Action<d>(this.attach_d), new Action<d>(this.detach_d));
			this._Vuelo2 = default(EntityRef<Vuelo>);
			this._Vuelo1 = default(EntityRef<Vuelo>);
			this._Aeropuerto = default(EntityRef<Aeropuerto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					if (this._Vuelo1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ciudad_Origen", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Ciudad_Origen
		{
			get
			{
				return this._Ciudad_Origen;
			}
			set
			{
				if ((this._Ciudad_Origen != value))
				{
					if (this._Aeropuerto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCiudad_OrigenChanging(value);
					this.SendPropertyChanging();
					this._Ciudad_Origen = value;
					this.SendPropertyChanged("Ciudad_Origen");
					this.OnCiudad_OrigenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ciudad_Destino", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Ciudad_Destino
		{
			get
			{
				return this._Ciudad_Destino;
			}
			set
			{
				if ((this._Ciudad_Destino != value))
				{
					this.OnCiudad_DestinoChanging(value);
					this.SendPropertyChanging();
					this._Ciudad_Destino = value;
					this.SendPropertyChanged("Ciudad_Destino");
					this.OnCiudad_DestinoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroVuelo", DbType="Int NOT NULL")]
		public int NumeroVuelo
		{
			get
			{
				return this._NumeroVuelo;
			}
			set
			{
				if ((this._NumeroVuelo != value))
				{
					this.OnNumeroVueloChanging(value);
					this.SendPropertyChanging();
					this._NumeroVuelo = value;
					this.SendPropertyChanged("NumeroVuelo");
					this.OnNumeroVueloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Precio", DbType="Int NOT NULL")]
		public int Precio
		{
			get
			{
				return this._Precio;
			}
			set
			{
				if ((this._Precio != value))
				{
					this.OnPrecioChanging(value);
					this.SendPropertyChanging();
					this._Precio = value;
					this.SendPropertyChanged("Precio");
					this.OnPrecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Moneda", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Moneda
		{
			get
			{
				return this._Moneda;
			}
			set
			{
				if ((this._Moneda != value))
				{
					this.OnMonedaChanging(value);
					this.SendPropertyChanging();
					this._Moneda = value;
					this.SendPropertyChanged("Moneda");
					this.OnMonedaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_habilitado", DbType="Int")]
		public System.Nullable<int> habilitado
		{
			get
			{
				return this._habilitado;
			}
			set
			{
				if ((this._habilitado != value))
				{
					this.OnhabilitadoChanging(value);
					this.SendPropertyChanging();
					this._habilitado = value;
					this.SendPropertyChanged("habilitado");
					this.OnhabilitadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Vuelo_d", Storage="_d", ThisKey="NumeroVuelo", OtherKey="Vuelo")]
		public EntitySet<d> d
		{
			get
			{
				return this._d;
			}
			set
			{
				this._d.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Vuelo_Vuelo", Storage="_Vuelo2", ThisKey="id", OtherKey="id", IsUnique=true, IsForeignKey=false)]
		public Vuelo Vuelo2
		{
			get
			{
				return this._Vuelo2.Entity;
			}
			set
			{
				Vuelo previousValue = this._Vuelo2.Entity;
				if (((previousValue != value) 
							|| (this._Vuelo2.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Vuelo2.Entity = null;
						previousValue.Vuelo1 = null;
					}
					this._Vuelo2.Entity = value;
					if ((value != null))
					{
						value.Vuelo1 = this;
					}
					this.SendPropertyChanged("Vuelo2");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Vuelo_Vuelo", Storage="_Vuelo1", ThisKey="id", OtherKey="id", IsForeignKey=true)]
		public Vuelo Vuelo1
		{
			get
			{
				return this._Vuelo1.Entity;
			}
			set
			{
				Vuelo previousValue = this._Vuelo1.Entity;
				if (((previousValue != value) 
							|| (this._Vuelo1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Vuelo1.Entity = null;
						previousValue.Vuelo2 = null;
					}
					this._Vuelo1.Entity = value;
					if ((value != null))
					{
						value.Vuelo2 = this;
						this._id = value.id;
					}
					else
					{
						this._id = default(int);
					}
					this.SendPropertyChanged("Vuelo1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Aeropuerto_Vuelo", Storage="_Aeropuerto", ThisKey="Ciudad_Origen", OtherKey="Ciudad", IsForeignKey=true)]
		public Aeropuerto Aeropuerto
		{
			get
			{
				return this._Aeropuerto.Entity;
			}
			set
			{
				Aeropuerto previousValue = this._Aeropuerto.Entity;
				if (((previousValue != value) 
							|| (this._Aeropuerto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Aeropuerto.Entity = null;
						previousValue.Vuelo.Remove(this);
					}
					this._Aeropuerto.Entity = value;
					if ((value != null))
					{
						value.Vuelo.Add(this);
						this._Ciudad_Origen = value.Ciudad;
					}
					else
					{
						this._Ciudad_Origen = default(string);
					}
					this.SendPropertyChanged("Aeropuerto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_d(d entity)
		{
			this.SendPropertyChanging();
			entity.Vuelo1 = this;
		}
		
		private void detach_d(d entity)
		{
			this.SendPropertyChanging();
			entity.Vuelo1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pasajero")]
	public partial class Pasajero : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _Nombre;
		
		private string _Correo;
		
		private int _Telefono;
		
		private System.Nullable<int> _Habilitado;
		
		private EntitySet<d> _d;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnCorreoChanging(string value);
    partial void OnCorreoChanged();
    partial void OnTelefonoChanging(int value);
    partial void OnTelefonoChanged();
    partial void OnHabilitadoChanging(System.Nullable<int> value);
    partial void OnHabilitadoChanged();
    #endregion
		
		public Pasajero()
		{
			this._d = new EntitySet<d>(new Action<d>(this.attach_d), new Action<d>(this.detach_d));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this.OnCorreoChanging(value);
					this.SendPropertyChanging();
					this._Correo = value;
					this.SendPropertyChanged("Correo");
					this.OnCorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="Int NOT NULL")]
		public int Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Habilitado", DbType="Int")]
		public System.Nullable<int> Habilitado
		{
			get
			{
				return this._Habilitado;
			}
			set
			{
				if ((this._Habilitado != value))
				{
					this.OnHabilitadoChanging(value);
					this.SendPropertyChanging();
					this._Habilitado = value;
					this.SendPropertyChanged("Habilitado");
					this.OnHabilitadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pasajero_d", Storage="_d", ThisKey="Nombre", OtherKey="Persona")]
		public EntitySet<d> d
		{
			get
			{
				return this._d;
			}
			set
			{
				this._d.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_d(d entity)
		{
			this.SendPropertyChanging();
			entity.Pasajero = this;
		}
		
		private void detach_d(d entity)
		{
			this.SendPropertyChanging();
			entity.Pasajero = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Contacto")]
	public partial class Contacto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _correo;
		
		private string _mensaje;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OncorreoChanging(string value);
    partial void OncorreoChanged();
    partial void OnmensajeChanging(string value);
    partial void OnmensajeChanged();
    #endregion
		
		public Contacto()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this.OncorreoChanging(value);
					this.SendPropertyChanging();
					this._correo = value;
					this.SendPropertyChanged("correo");
					this.OncorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mensaje", DbType="VarChar(450) NOT NULL", CanBeNull=false)]
		public string mensaje
		{
			get
			{
				return this._mensaje;
			}
			set
			{
				if ((this._mensaje != value))
				{
					this.OnmensajeChanging(value);
					this.SendPropertyChanging();
					this._mensaje = value;
					this.SendPropertyChanged("mensaje");
					this.OnmensajeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
